//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleDriveFiles
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string GoogleDrive_ID { get; set; }
        public string DownloadURL { get; set; }
        public int EventID { get; set; }
        public string FileSize { get; set; }
    
        public virtual tblScheduleData tblScheduleData { get; set; }
    }
}
