//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDisciplinesMapping
    {
        public int ID { get; set; }
        public int DisciplineID { get; set; }
        public int TeacherID { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual tblDisciplines tblDisciplines { get; set; }
        public virtual tblTeachers tblTeachers { get; set; }
    }
}
