//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScheduleData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblScheduleData()
        {
            this.GoogleDriveFiles = new HashSet<GoogleDriveFiles>();
        }
    
        public int ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Type { get; set; }
        public string Room { get; set; }
        public string Topic { get; set; }
        public string FilePath { get; set; }
        public int TeacherID { get; set; }
        public int DisciplineID { get; set; }
    
        public virtual tblDisciplines tblDisciplines { get; set; }
        public virtual tblTeachers tblTeachers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoogleDriveFiles> GoogleDriveFiles { get; set; }
    }
}
