//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebSiteDBEntities : DbContext
    {
        public WebSiteDBEntities()
            : base("name=WebSiteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblLogin> tblLogin { get; set; }
        public virtual DbSet<tblNews> tblNews { get; set; }
        public virtual DbSet<tblStudents> tblStudents { get; set; }
        public virtual DbSet<tblDisciplines> tblDisciplines { get; set; }
        public virtual DbSet<tblDisciplinesMapping> tblDisciplinesMapping { get; set; }
        public virtual DbSet<tblTeachers> tblTeachers { get; set; }
        public virtual DbSet<tblScheduleData> tblScheduleData { get; set; }
        public virtual DbSet<GoogleDriveFiles> GoogleDriveFiles { get; set; }

        public System.Data.Entity.DbSet<WebSite.ViewModels.TeachersViewModel.TeachersViewModel> TeachersViewModels { get; set; }
    }
}
